apiVersion: v1
kind: ReplicationController
metadata:
  name: chatbot-rc
spec:
  replicas: 3
  selector:
    app: chatbot
  template:
    metadata:
      name: chatbot-pod
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: gcr.io/zinc-epigram-278008/chatbot:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080